### ISSUE TITLE
Multiline Comment not Closed before EOF - Incorrect

### ISSUE THREAD

**Issue by king2b3** [stegnerw/compiler_theory_test_programs#16]
Should cause an error, should we still compile?

EX
.
.
.
end program .

/* this is the end of the file

**Comment by stegnerw** [comment]
I wrote my scanner so that it will assume a closure of the comment when it hits EOF and raise a warning. I personally think it is more appropriate for the scanner to raise a warning rather than an error, then let the parser decide if it can properly parse the file. My reasoning is that the comments don't make it past the scanner, so if the unclosed block comment is before the end program, the scanner will not see the end program token and this will produce an error. So I would say the unclosed block comment should be an incorrect case only if it comments out the end program token. What do you think?

**Comment by stegnerw** [comment]
I'll go ahead and add this to one of my cases in my branch. It will only throw a warning on my code, but I will still add it in the `incorrect/` directory because ideally the `correct/` examples should not have warnings or errors. Or at least I like to think correct code should be warning free. :)

**Comment by stegnerw** [comment]
Update: Added a case for this in a commit on my branch: 8e5c1702caa3447730fcc0548fd31dffb5632bfe
