### ISSUE TITLE
Scoping - Global redefined in local scope - Incorrect

### ISSUE THREAD

**Issue by king2b3** [stegnerw/compiler_theory_test_programs#17]
A global variable is redefined in a local space

Ex

global variable x : integer;

procedure Test : integer(variable val1 : integer)
.
.
.
variable x : boolean;

**Comment by stegnerw** [comment]
@king2b3 I do believe this is actually a correct usage. There are some examples of this in the correct test files Dr. Wilsey provided. Unless I misunderstand what this test case means.

Close this issue if you meant making a local variable shadow a global variable.

**Comment by stegnerw** [comment]
There is an example of shadowing in `correct/math.src` where the global `tmp2` is shadowed locally in the function, but this is legal due to scoping rules. There is another shadowing example in `correct/test1b.src` where local `int i` in procedure `if_proc` is shadowed by local `float i` in procedure `dummy`.

In case where you mean you cannot redefine a global, `incorrect/test1.src` redefines the global `zach`, so I believe this issue is already covered.

Please reopen it with a comment elaborating if you think that this issue is not covered by any of the examples I mentioned.
